package com.camriders.filters

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
				if ((controllerName+':'+actionName) in ['stream:view', 'stream:list']) {
					return true
				  } else {

                // Access control by convention.
                accessControl()
				  }
            }
        }
    }
}
